services/web/project/models.py
from datetime import datetime

from flask_login import UserMixin

from . import db


class Patient(UserMixin, db.Model):
    __table_args__ = {"extend_existing": True}
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    name = db.Column(db.String(1000), unique=True)
    exams = db.relationship("Exam", backref="patient", lazy=True)
    notes = db.relationship("Note", backref="patient", lazy=True)
    password = db.Column(db.String(100))
    no_pregnancies = db.Column(db.Integer, default=0)
    height = db.Column(db.Integer, default=0)
    weight = db.Column(db.Integer, default=0)
    in_labour = db.Column(db.Float, default=0)
    profile_init = db.Column(db.Boolean, default=False)
    email_confirmed = db.Column(db.Boolean, default=False)

class Exam(db.Model):
    __table_args__ = {"extend_existing": True}
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(1000), db.ForeignKey("patient.name"), nullable=False)
    dilation = db.Column(db.Integer, default=0)
    effacement = db.Column(db.Integer, default=0)
    station = db.Column(db.Integer, default=0)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

class Note(db.Model):
    __table_args__ = {"extend_existing": True}
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(1000), db.ForeignKey("patient.name"), nullable=False)
    note = db.Column(db.String(1000))
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

# class User(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     username = db.Column(db.String(64), index=True, unique=True)
#     email = db.Column(db.String(120), index=True, unique=True)
#     password_hash = db.Column(db.String(128))
#     posts = db.relationship('Post', backref='author', lazy='dynamic')

#     def __repr__(self):
#         return '<User {}>'.format(self.username)

# class Post(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     body = db.Column(db.String(140))
#     timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
#     user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

#     def __repr__(self):
#         return '<Post {}>'.format(self.body)

# def init_db():
#     db.create_all()

# if __name__ == '__main__':
#     init_db()

services/web/project/__init__.py
import os

from werkzeug.utils import secure_filename
from flask import (
    Flask,
    jsonify,
    send_from_directory,
    request,
    redirect,
    url_for
)
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy



app = Flask(__name__)
app.config.from_object("project.config.Config")
db = SQLAlchemy(app)

login_manager = LoginManager()
login_manager.login_view = "auth.login"
login_manager.init_app(app)

from .models import Patient

@login_manager.user_loader
def load_user(user_id):
    # since the user_id is just the primary key of our user table, use it in the query for the user
    return Patient.query.get(int(user_id))

# blueprint for auth routes in our app
from .auth import auth as auth_blueprint

app.register_blueprint(auth_blueprint)

# blueprint for non-auth parts of app
from .main import main as main_blueprint

app.register_blueprint(main_blueprint)

services/web/project/auth.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, login_user, logout_user
from werkzeug.security import check_password_hash, generate_password_hash

from . import db
from .models import Patient, Exam
from .util import send_email, ts

auth = Blueprint("auth", __name__)


@auth.route("/login")
def login():
    return render_template("login.html")


@auth.route("/login", methods=["POST"])
def login_post():
    email = request.form.get("email")
    password = request.form.get("password")
    remember = True if request.form.get("remember") else False

    user = Patient.query.filter_by(email=email).first()

    # check if user actually exists
    # take the user supplied password, hash it, and compare it to the hashed password in database
    if not user:
        flash("Patient not found. Please Sign Up.")
        return redirect(url_for("auth.signup"))
    elif not user.email_confirmed:
        flash(
            "Please confirm your e-mail before logging in. An email has been sent to {}.".format(
                user.email
            )
        )
        generate_user_email(user.email)
        return redirect(url_for("auth.login"))
    elif not check_password_hash(user.password, password):
        flash("Please check your login details and try again.")
        return redirect(url_for("auth.login"))

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)

    return redirect(url_for("main.profile"))


@auth.route("/signup")
def signup():
    return render_template("signup.html")


@auth.route("/signup", methods=["POST"])
def signup_post():

    email = request.form.get("email")
    name = request.form.get("name")
    password = request.form.get("password")

    user = Patient.query.filter_by(
        email=email
    ).first()  # if this returns a user, then the email already exists in database

    if (
        user
    ):  # if a user is found, we want to redirect back to signup page so user can try again
        flash("Email address already exists")
        return redirect(url_for("auth.signup"))

    # create new user with the form data. Hash the password so plaintext version isn't saved.
    new_user = Patient(
        email=email,
        name=name,
        password=generate_password_hash(password, method="sha256"),
    )

    generate_user_email(email)

    # add the new user to the database
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for("auth.login"))


@auth.route("/confirm/<token>")
def confirm_email(token):
    try:
        email = ts.loads(token, salt="email-confirm-key", max_age=86400)
    except Exception:
        # flake8: noqa: F821
        abort(404)

    user = Patient.query.filter_by(email=email).first_or_404()

    user.email_confirmed = True

    db.session.add(user)
    db.session.commit()

    return redirect(url_for("auth.login"))


@auth.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.index"))


def generate_user_email(email):
    # Now we'll send the email confirmation link
    subject = "Baby Curve - Confirm your email"

    token = ts.dumps(email, salt="email-confirm-key")

    confirm_url = url_for("auth.confirm_email", token=token, _external=True)

    html = render_template("email/activate.html", confirm_url=confirm_url)

    # We'll assume that send_email has been defined in myapp/util.py
    send_email(email, subject, html)

services/web/project/main.py
import time
from datetime import datetime
from flask import Blueprint, flash, redirect, render_template, request, session, url_for
from flask_login import current_user, login_required
from werkzeug.security import check_password_hash, generate_password_hash

from . import db
from .models import Patient, Exam, Note

from .views import plot_labour

main = Blueprint("main", __name__)


@main.route("/")
def index():
    return render_template("index.html")


@main.route("/profile")
@login_required
def profile():
    user = Patient.query.filter_by(email=current_user.email).first()
    
    if user.profile_init:
        return render_template(
            "profile.html",
            user=current_user,
        )
    else:
        return render_template(
            "init_profile.html",
            user=current_user,
            pregs=[i for i in range(10)],
            height=[i for i in range(200)],
            weight=[i for i in range(300)],
        )

@main.route("/update_profile")
@login_required
def update_profile():
    user = Patient.query.filter_by(email=current_user.email).first()
    user.profile_init = False
    db.session.commit()
    return redirect(url_for("main.profile"))

@main.route("/init_profile", methods=["POST"])
@login_required
def init_profile():
    prev_pregs = request.form.get("prev_pregs")
    height = request.form.get("height")
    weight = request.form.get("weight")

    user = Patient.query.filter_by(email=current_user.email).first()

    if height and weight:
        user.no_pregnancies = prev_pregs
        user.height = height
        user.weight = weight
        user.profile_init = True
        db.session.commit()
        flash("Profile successully updated.")
    else:
        flash("Error updating profile.")

    return redirect(url_for("main.profile"))

@main.route("/graph")
@login_required
def graph():
    hist_plot = plot_labour(current_user)
    return render_template(
        "graph.html",
        history=hist_plot,
    )


@main.route("/new_exam")
@login_required
def new_exam():
    return render_template(
        "new_exam.html",
        user=current_user,
        dilation=[i for i in range(-10, 10)],
        effacement=[i for i in range(-10, 10)],
        station=[i for i in range(-10, 10)],
    )

@main.route("/labor_status", methods=["POST"])
@login_required
def labor_status():

    user = Patient.query.filter_by(email=current_user.email).first()

    user.in_labour = time.time()

    db.session.commit()

    return redirect(url_for("main.profile"))


@main.route("/notes")
@login_required
def notes():
    return render_template("notes.html")

@main.route("/submit_exam", methods=["POST"])
@login_required
def submit_exam():
    dilation = request.form.get("dilation")
    effacement = request.form.get("effacement")
    station = request.form.get("station")

    exam = Exam(name=current_user.name, dilation=dilation, effacement=effacement, station=station)
    
    db.session.add(exam)
    db.session.commit()

    flash("Exam data added.")

    return redirect(url_for("main.graph"))


@main.route("/submit_note", methods=["POST"])
@login_required
def submit_note():
    note_text = request.form.get("notes")

    note = Note(name=current_user.name, note=note_text)
    
    db.session.add(note)
    db.session.commit()

    flash("Exam data added.")

    return redirect(url_for("main.graph"))
    

@main.route("/user_password_change", methods=["POST"])
@login_required
def user_password_change():
    old_pass = request.form.get("old_pw")
    new_pass1 = request.form.get("pw1")
    new_pass2 = request.form.get("pw2")

    user = Patient.query.filter_by(email=current_user.email).first()

    if check_password_hash(user.password, old_pass):
        if new_pass1 == new_pass2:
            user.password = generate_password_hash(new_pass1, method="sha256")
            # db.session.add(user)
            db.session.commit()
            flash("Password has been updated.", "success")
            return redirect(url_for("main.profile"))
        else:
            flash("The new password entries do not match.")
    else:
        flash("The old password is incorrect.")

    return render_template("update_password.html")


@main.route("/update_password")
@login_required
def update_password():
    return render_template("update_password.html")

services/web/project/util/__init__.py
from .helpers import (
    send_email,
)
from .security import ts

services/web/project/views.py
import json
from datetime import datetime
import plotly
import plotly.graph_objs as go
from flask_table import Col, Table

from .models import Patient, Exam, Note

def plot_labour(user):

    user_time = datetime.fromtimestamp(user.in_labour)
    exams = Exam.query.filter_by(name=user.name).all()
    notes = Note.query.filter_by(name=user.name).all()

    exam_data = {
        "time": [],
        "dilation": [],
        "bishops": [],
    }
    for ex in exams:
        exam_data["time"].append(ex.timestamp)
        exam_data["dilation"].append(ex.dilation)
        exam_data["bishops"].append(ex.dilation + ex.effacement + ex.station)

    ref_data = {
        "time": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        "dilation": [0, 0, 2, 3, 4, 5, 5, 7, 8, 9, 10],
    }

    t_min = min(ref_data["time"])
    t_max = max(ref_data["time"])
    y_max = max(ref_data["dilation"])

    note_data = {
        "time": [],
        "note": [],
    }

    for note in notes:
        note_data["time"].append(note.timestamp)
        note_data["note"].append(note.note)

    N =  len(note_data["time"])
    line_data = [
        # go.Scatter(mode="lines", x=ref_data["time"], y=ref_data["dilation"],),
        go.Scatter(mode="markers+lines", x=ref_data["time"], y=ref_data["dilation"], name="Dilation"),
        go.Scatter(mode="lines", x=[user_time, user_time], y=[0, y_max], name="Entered Labor"),
        go.Scatter(mode="markers", x=note_data["time"], y=[10]*N,text=note_data["note"], name="Patient notes"),
        # go.Scatter(mode="lines", x=ref_data["time"], y=df_exam.bishops,)

    ]

    layout = go.Layout(paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)")

    ln_fig = go.Figure(data=line_data, layout=layout)

    ln_fig.update_xaxes(showgrid=False, title_text="time")
    ln_fig.update_yaxes(showgrid=True, title_text="dilation")

    ln_json = json.dumps(ln_fig, cls=plotly.utils.PlotlyJSONEncoder)

    return ln_json

services/web/project/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Baby curve fitting.</title>
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.9.0/css/bulma.min.css" /> -->
    <!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" /> -->
    <link
      rel="icon"
      type="image/png"
      href="https://www.freepngimg.com/thumb/emoji/64983-emoticon-sunglasses-smiley-iphone-go-emoji.png"
    />
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"> -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"> -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css"
      type="text/css"
    />
    <link
      rel="stylesheet"
      href="https://pingendo.com/assets/bootstrap/bootstrap-4.0.0-beta.1.css"
      type="text/css"
    />
    <style media="screen" type="text/css">
      /*https://coolors.co/697074-feebee-cddae3-e1f0fa-f7e0e3*/
      /*
      
      */
      * {
        font-family: Arial, Helvetica, sans-serif;
      }
      body {
        background-color: #feebee;
        padding-bottom: 70px;
      }

      input {
        width: 100%;
      }
      section {
        padding-top: 20px;
      }

      h1 {
        color: #697074;
        padding-top: 50px;
      }
      h2 {
        color: #9aa4aa;
        padding-top: 30px;
      }
      h3 {
        color: #a9d1ea;
        padding-top: 10px;
      }
      p {
        color: #5F6669;
        padding-top: 10px;
      }

      table {
        border-collapse: collapse;
        width: 100%;
        font-size: medium;
      }

      td,
      th {
        border: 1px solid #697074;
        text-align: center;
        padding: 8px;
        cursor: pointer;
      }

      tr:nth-child(even) {
        background-color: #98959b;
      }

      input[type="text"],
      input[type="password"],
      input[type="email"] {
        font-size: 16px;
        padding: 20px 20px;
        margin: 20px 0;
        box-sizing: border-box;
        border: 2px #E69EA7;
        border-radius: 10px;
        width: 100%;
        /*max-width: 600px*/
      }

      .button {
        background-color: #E1F0FA;
        border: none;
        color: #5F6669;
        padding: 16px 32px;
        text-align: center;
        font-size: 16px;
        margin: 4px 2px;
        transition: 0.3s;
        width: 100%;
        /*max-width: 600px*/
      }

      .button:hover {
        background-color: #FDB7C2;
      }

      .dropup .dropdown-menu {
        top: auto;
        bottom: 100%;
        /*left: -100%;*/
        margin-bottom: 20px;
        /*color: white;*/
      }
      .fa {
        line-height: 40px;
        vertical-align: middle;
        color: #a9d1ea;
      }
      .nav-link {
        color: #a9d1ea;
      }

      #text {
        color: #feebee;
      }

      #dup_butt {
        color: #a9d1ea;
        background-color: #697074;
        border-color: #697074;
      }
      .bg-dark {
        background-color: #697074 !important;
      }

      .slider {
        -webkit-appearance: none;
        width: 100%;
        height: 25px;
        background: #d3d3d3;
        outline: none;
        opacity: 0.7;
        -webkit-transition: .2s;
        transition: opacity .2s;
      }

      .slider:hover {
        opacity: 1;
      }

      .slider::-webkit-slider-thumb {
        -webkit-appearance: none;
        appearance: none;
        width: 25px;
        height: 25px;
        background: #a9d1ea;
        cursor: pointer;
      }

      .slider::-moz-range-thumb {
        width: 25px;
        height: 25px;
        background: #a9d1ea;
        cursor: pointer;
      }
    </style>
  </head>
  <body>
    {% if current_user.is_authenticated %}
    {% if not current_user.in_labour%}
    <!-- LABOR BUTTON - CUSTOM !-->
    <section>
      <div>
      <form name="labor_status" id="labor_status" action="{{ url_for('main.labor_status') }}" method="POST">
        <button class="button is-block is-info is-large is-fullwidth">
            CLICK HERE IF YOU ARE NOW IN LABOR.
        </button>
      </form>
      </div>
    </section>
    {% endif %}
    {% endif %}

    <!-- START PAGE BOTTOM - CUSTOM !-->
    <section>
      <div>
        <div class="container has-text-centered">
          {% block content %} {% endblock %}
        </div>
      </div>
    </section>
    <!-- END PAGE BOTTOM - CUSTOM !-->
    <!-- START NAVBAR BOTTOM - CUSTOM !-->
    <nav class="navbar fixed-bottom navbar-dark bg-dark">
      <div class="container p-0">
        <!-- Default dropup button -->
        <div class="btn-group dropup btn-group-sm" style="color: blue">
          {% if current_user.is_authenticated %}
          <button
            type="button"
            class="btn dropdown-toggle btn-warning"
            aria-expanded="false"
            aria-haspopup="true"
            data-toggle="dropdown"
            id="dup_butt"
          >
            <i class="fa fa-user fa-lg"></i>
            <span id="text">&nbsp;{{ current_user.name }}</span>
          </button>
          <div class="dropdown-menu text-left">
            <a href="{{ url_for('auth.logout') }}" class="dropdown-item">
              logout
            </a>
            <div class="dropdown-divider"></div>
            {% if current_user.is_admin %}
            <a href="{{ url_for('main.update') }}" class="dropdown-item">
              admin
            </a>
            {% endif %}
            <a
              href="{{ url_for('main.update_password') }}"
              class="dropdown-item"
            >
              update password
            </a>
            <a href="{{ url_for('main.profile') }}" class="dropdown-item">
              profile
            </a>
          </div>
        </div>
        <!-- START NAVBAR BOTTOM - NAV LEFT - CUSTOM !-->
        <nav class="nav">
          <a
            class="nav-link text-warning px-0 pr-4"
            href="{{ url_for('main.new_exam') }}"
          >
            <i class="fa fa-diagnoses fa-lg"></i>
            <span id="text">&nbsp;new exam</span>
          </a>
        </nav>
        <nav class="nav">
          <a
            class="nav-link text-warning px-0 pr-4"
            href="{{ url_for('main.graph') }}"
          >
            <i class="fa fa-chart-line fa-lg"></i>
            <span id="text">&nbsp;graph</span>
          </a>
        </nav>
        <nav class="nav">
          <a
            class="nav-link text-warning px-0 pr-4"
            href="{{ url_for('main.notes') }}"
          >
            <i class="fa fa-notes-medical fa-lg"></i>
            <span id="text">&nbsp;notes</span>
          </a>
        </nav>
        {% endif %} {% if not current_user.is_authenticated %}
        <nav class="nav">
          <a
            class="nav-link text-warning px-0 pr-4"
            href="{{ url_for('auth.login') }}"
          >
            <i class="fa fa-sign-in-alt fa-lg"></i>
            <span id="text">&nbsp;login</span>
          </a>
          <a
            class="nav-link text-warning px-0 pr-4"
            href="{{ url_for('auth.signup') }}"
          >
            <i class="fa fa-user-plus fa-lg"></i>
            <span id="text">&nbsp;sign up</span>
          </a>
        </nav>
        {% endif %}
        <!-- END NAVBAR BOTTOM - NAV LEFT - CUSTOM !-->
      </div>
    </nav>
    <!-- END NAVBAR BOTTOM - CUSTOM !-->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"
      integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"
      integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

services/web/project/templates/graph.html
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
 -->
{% extends "base.html" %} {% block content %}

{% with messages =
get_flashed_messages() %} {% if messages %}
<div class="notification is-danger" style="text-align: center">
  {{ messages[0] }}
</div>
{% endif %} {% endwith %}

<h1 class="title">labour trajectory</h1>
<section>
  <div>
    <div class="chart" id="chart">
      <script style="width: 100%">
        var graphs = {{ history | safe }};
        Plotly.plot('chart',graphs,{});
      </script>
    </div>
  </div>
</section>
{% endblock %}

services/web/project/templates/init_profile.html
{% extends "base.html" %} {% block content %} {% with messages =
get_flashed_messages() %} {% if messages %}
<div class="notification is-danger" style="text-align: center">
  {{ messages[0] }}
</div>
{% endif %} {% endwith %}

<section>
  <h2 class="title">{{ user.name }}, add your history.</h2>
  <form name="Select" action="{{ url_for('main.init_profile') }}" method="POST">
    <div>
    <label for="prev_pregs">Number of Previous Pregnancies:</label><select
      class="dropbtn is-block ids-fullwidth"
      name="prev_pregs"
      type="text"
      placeholder="Number of previous pregnancies."
      style="width: 100%"
      id="prev_pregs"
    >
      {% for no in pregs %}
      <option>{{ no }}</option>
      {% endfor %}
    </select>
  </div>
  <div>
        <label for="height">Height (cm):</label><select
      class="dropbtn is-block ids-fullwidth"
      name="height"
      type="text"
      placeholder="Height (cm)."
      style="width: 100%"
      id="height"
    >
      {% for ht in height %}
      <option>{{ ht }}</option>
      {% endfor %}
    </select>
    </div>
    <div>
        <label for="weight">Weight (lb):</label><select
      class="dropbtn is-block ids-fullwidth"
      name="weight"
      type="text"
      placeholder="Weight (lb)."
      style="width: 100%"
      id="weight"
    >
      {% for wt in weight %}
      <option>{{ wt }}</option>
      {% endfor %}
    </select>
    </div>
    <div>
    <button class="button is-block is-info is-large is-fullwidth">
      Submit
    </button>
    </div>
  </form>
</section>
{% endblock %}

services/web/project/templates/new_exam.html
{% extends "base.html" %} {% block content %} {% with messages =
get_flashed_messages() %} {% if messages %}
<div class="notification is-danger" style="text-align: center">
  {{ messages[0] }}
</div>
{% endif %} {% endwith %}

<section>
  <h2 class="title">{{ user.name }}, add your exam info.</h2>
      <div>
  <form name="exam" id="exam" action="{{ url_for('main.submit_exam') }}" method="POST" oninput="x.value=parseInt(dilation.value)+parseInt(effacement.value) + +parseInt(station.value)">

  <p>Dilation: <span id="dil_demo"></span> cm</p>
  <input type="range" class="slider" min="0" max="20" id="dilation" name="dilation" value="10">
  <br>

  <p>Effacement: <span id="eff_demo"></span> cm</p>
  <input type="range" class="slider" min="0" max="30" id="effacement" name="effacement" value="10">
  <br>

  <p>Station: <span id="sta_demo"></span> cm</p>
  <input type="range" class="slider" min="0" max="40" id="station" name="station" value="10">


  <br>
  <div style="text-align: center" >
  <label for="bishop">Bishop's Score:</label>
  <output name="x" for="dilation effacement station" value="0"></output><br>
</div>
  <button class="button is-block is-info is-large is-fullwidth">
      Submit Exam Info.
  </button>
</form>
    </div>
</section>

<script>
  var dil_slider = document.getElementById("dilation");
  var dil_output = document.getElementById("dil_demo");
  dil_output.innerHTML = dil_slider.value;

  dil_slider.oninput = function() {
    dil_output.innerHTML = this.value;
  }

  var eff_slider = document.getElementById("effacement");
  var eff_output = document.getElementById("eff_demo");
  eff_output.innerHTML = eff_slider.value;

  eff_slider.oninput = function() {
    eff_output.innerHTML = this.value;
  }

  var sta_slider = document.getElementById("station");
  var sta_output = document.getElementById("sta_demo");
  sta_output.innerHTML = sta_slider.value;

  sta_slider.oninput = function() {
    sta_output.innerHTML = this.value;
  }
</script>

{% endblock %}

services/web/project/templates/notes.html
{% extends "base.html" %} {% block content %}
<div>

<section>
  {% with messages = get_flashed_messages() %} {% if messages %}
  <div class="notification is-danger" style="text-align: center">
    {{ messages[0] }}
  </div>
  {% endif %} {% endwith %}
</section>

<h1 class="title">Add note.</h1>
  <form name="notes" action="{{ url_for('main.submit_note') }}" method="POST">
    <textarea rows="10" name="notes" , style="width: 100%"></textarea>
    <button class="button is-block is-info is-large is-fullwidth">
      Add note.
    </button>
  </form>
</section>
</div>
{% endblock %}

services/web/project/templates/profile.html
{% extends "base.html" %} {% block content %} {% with messages =
get_flashed_messages() %} {% if messages %}
<div class="notification is-danger" style="text-align: center">
  {{ messages[0] }}
</div>
{% endif %} {% endwith %}
<h1 class="title" style="text-align: center">
  {{ user.name }}
</h1>
<section>
  <div>
    <h3 class="title" style="text-align: center">patient data</h3>
    Height: {{ user.height }} cm<br>
    Weight: {{ user.weight }} lb<br>
    Number of Pregnancies: {{ user.no_pregnancies }}<br>
  </div>
</section>
<section>
  <div>
    <h2 class="title">user admin</h2>
    <a href="{{ url_for('main.update_profile') }}">update profile</a><br>
    <a href="{{ url_for('main.update_password') }}">update password</a><br>
  </div>
</section>
{% endblock %}

services/web/project/templates/update_password.html
{% extends "base.html" %} {% block content %} {% with messages =
get_flashed_messages() %} {% if messages %}
<div class="notification is-danger" style="text-align: center">
  {{ messages[0] }}
</div>
{% endif %} {% endwith %}
<form action="{{ url_for('main.user_password_change') }}" method="POST">
  <div class="field">
    <div class="control">
      <input
        class="input is-large"
        type="password"
        name="old_pw"
        placeholder="Current Password"
        autofocus=""
      />
    </div>
  </div>

  <div class="field">
    <div class="control">
      <input
        class="input is-large"
        type="password"
        name="pw1"
        placeholder="New Password"
        autofocus=""
      />
    </div>
  </div>

  <div class="field">
    <div class="control">
      <input
        class="input is-large"
        type="password"
        name="pw2"
        placeholder="New Password"
      />
    </div>
  </div>

  <button class="button">Update</button>
</form>
{% endblock %}